### ISSUE TITLE
update tc configs for older kernel support in glibc

### ISSUE THREAD

**Issue by mmlb** [mistifyio/mistify-os#164]

**Comment by StevenIsaacs** [comment]
To get this working with the nightly builds I need to wipe some workspaces on the server. We also want this to be the same for both the base and sdk variants.

**Comment by StevenIsaacs** [comment]
Some of the difficulty of this change could be eliminated if the `buildmistify` script handled the `--toolchainreset` option properly. Changing the toolchain like this also requires a reset of `buildroot` and `go` because they either copy toolchain components or reference them. I'm updating `buildmistify` to deal with this but because of the type of change a number of builds are needed to verify all works.

**Comment by mmlb** [comment]
sgtm I'll rebase once you merge that into `buildmistify`
